# This image is only meant to be built from within the build.sh script.
FROM centos:latest

# Copy binaries (placed by build.sh)
COPY base/tikv-server /

ADD config.toml /etc/tikv/
ADD bin/mountpath /usr/local/bin/

EXPOSE 20160

CMD ["/tikv-server"]